// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVYQIRKBc03ZIn0qwQ8lTRP_zgJYir0CU',
    appId: '1:580899785281:web:4584d92e973331153894c0',
    messagingSenderId: '580899785281',
    projectId: 'fir-analytics-20853',
    authDomain: 'fir-analytics-20853.firebaseapp.com',
    storageBucket: 'fir-analytics-20853.appspot.com',
    measurementId: 'G-DVE6MQMF79',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAW_jCyYLfiSZTt5PbfSpDLqdig0KRF4QI',
    appId: '1:580899785281:android:1559bf125bb2513f3894c0',
    messagingSenderId: '580899785281',
    projectId: 'fir-analytics-20853',
    storageBucket: 'fir-analytics-20853.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFuNmMpuyF5Lid0G751UqpYYc3CWkZSSo',
    appId: '1:580899785281:ios:327bfcb1a18755613894c0',
    messagingSenderId: '580899785281',
    projectId: 'fir-analytics-20853',
    storageBucket: 'fir-analytics-20853.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyticsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCFuNmMpuyF5Lid0G751UqpYYc3CWkZSSo',
    appId: '1:580899785281:ios:0298ae5e1ba3ea8d3894c0',
    messagingSenderId: '580899785281',
    projectId: 'fir-analytics-20853',
    storageBucket: 'fir-analytics-20853.appspot.com',
    iosBundleId: 'com.example.firebaseAnalyticsApp.RunnerTests',
  );
}
